[package]
name = "shared"
version = "0.0.0"
authors = []
edition = "2021"

[dependencies]
spirv-std = { version = "*" }
bytemuck = { version = "1.20.0", features = ["derive"] }

[lints]
workspace = true
